### ISSUE TITLE
Restructure modules for project

### ISSUE THREAD

**Issue by derek63** [esbtools/esb-message-admin#11]
Let's restructure the modules for the project in the following fashion

**pom**
  dependencyManagement

**common**
  EsbMessage class 
  Header class
  Key (Metadata) class
  Entity classes for ^
  Search, Save and Key DAO ( and IMPL )

**app**
  Angular/webapp stuff
  REST Endpoints (/search, /sync, /key, admin)

**app-saml-auth**
  app Maven Overlay with SAML auth config

**rest-save**
  REST endpoint (/save)

**rest-save-cert-auth**
    rest-save Maven Overlay with CERT auth config

**rest-save-client**
  Java client for rest-save

**Comment by derek63** [comment]
@vritant @ykoer Thoughts on this proposed structure?

**Comment by vritant** [comment]
makes sense to me.

**Comment by vritant** [comment]
@derek63 the entity classes for the esb message and header will have to be shared as well, so perhaps we should add those to the model module as well ?

**Comment by ykoer** [comment]
@derek63 in which module are all the ORM, DAO and Service Facade stuff? I think that should be in a separate jar package and all war's would just have a dependency to it inside jboss-deployment-structure.xml

**Comment by vritant** [comment]
@ykoer  updated issue based on your comment and discussion with @derek63

**Comment by vritant** [comment]
closing issue post accepted pull request
