### ISSUE TITLE
current web context does not work.

### ISSUE THREAD

**Issue by vritant** [esbtools/esb-message-admin#5]
on calling curl -k https://[HOSTNAME]/esb%2Dmessage%2Dadmin%2Dapp%2D0%2E1%2E3%2ESNAPSHOT/api/key/tree/Entities

or curl -k https://[HOSTNAME]/esb%2Dmessage%2Dadmin/api/key/tree/Entities

I get a 404.

there are further changes required to make the deployed artifact work.

**Comment by derek63** [comment]
This should be fixed now that I added Maven war plugin to generate the deployment.  @vritant please confirm you are able to deploy the generated war on your end with the context path of /esb-message-admin
