### ISSUE TITLE
Gracefully handle session timeouts on the server

### ISSUE THREAD

**Issue by derek63** [esbtools/esb-message-admin#77]
Right now if your server session times while you have the application up in your browser, the front end doesn't really handle to any behind-the-scenes HTTP responses that don't return the expected REST content (like a 302 for a SAML re-login specifically), and instead just replaces the contents of the application with a blank page, forcing you to do a browser reload to make the application come back to life.

**Comment by alechenninger** [comment]
I can think of a few solutions to this... the simplest being: if we get a response from /api/ with content-type text/html, trigger a refresh of the page. We could also do something semi-fancy and try and keep track of the request that was trying to be made so that it is retried after the app is reloaded (now that a user is logged in). What do you think?

It'd be nice if Picketlink valve responded with a 403 but (as you may have seen from internal email) I can't get that to work, I suspect the bundled Picketlink module version we're using is <2.7.0.

**Comment by derek63** [comment]
I was thinking we could detect the 302 from the AjaxHttpRequest, but it seems there is no way to configure that to not follow redirects (the browser setting wins, which makes sense I guess), so we get forwarded right along to the login page and get back a 200 response. 

Looking at the content type may be our only option unless we can bundle a newer version of Picketlink in the app and force JBoss to use it instead of the bundled version (maybe require a custom valve that we also bundle with the app).  I have crudely implemented the content type/parsing the actual content before and it generally works well enough, however just looking at the content type might interpret a server error as a redirect, as JBoss returns text/html when a stack trace from the app is not handled (or generated internally and not handled).  So perhaps we'll need to look for (configurable!) bits of the login form in the content as well as checking that the content type is text/html (i.e. where content includes <some-identifyable-attribute-of-our-login-form>).

I do like the idea of trying to keep the original request around and satisfying it after the user has logged back in, but that wouldn't necessarily be essential.

**Comment by alechenninger** [comment]
So I think after our discussion today it comes down to essentially two options:

1. Make the frontend detect a SAML response from an AJAX call (via looking at content-type and something about the html to identify this is a saml thing), then deal with accordingly
2. Make the backend detect a SAML response from  an AJAX call (either by custom valve or upgrading to Picketlink 2.7.0 and sending X-Request-With header with ajax requests), then send to frontend as 401 or 403, make frontend deal with 401/403 accordingly

Where "deal with accordingly" is at the very least refresh the page to force a relogin, and could optionally store the request attempted in local storage or a cookie which the app knows to look for on load to replay, which wouldn't be too hard to implement methinks.

Option 2 is cleaner from a REST API perspective: a rest endpoint shouldn't really return an HTML page I think... a forbidden response would clearly be more semantically correct. But, it requires either a custom valve or upgrading Picketlink to >=2.7.0.

Option 1 is fairly straightforward to implement and is a little weird, but we at least know we have the SAML use case to deal with so I don't think it's _terrible_, but definitely a little ugly. Either way is kind of ugly honestly. SAML for REST is kinda :/

**Comment by alechenninger** [comment]
I realized that the /api distinction is actually wrong because this can happen with page loads too since its all ajax of course. I think everything else still applies tho

**Comment by derek63** [comment]
I agree that they are both kind of ugly...I say we do option 1 now to get this working, and open a few issues for making this better in the future:

1) Improve REST Error Handling - Make sure that REST endpoints handle all exceptions that can be generated and return appropriate response code and JSON formatted message.  This will help ensure that the REST endpoints never return an HTML content type with error stack traces.  Note that JBoss itself may still return HTML formatted errors/stacktraces for app server stuff, but all of those should return 500 response codes (so we can handle them that way vs content).

2) Try Picketlink 2.7.x bundling - If it works, remove content-type business for SAML and handle 401/403.  If it doesn't work, look at configuring existing Picketlink valve to allow for some kind of "session heartbeat" that can let us know when it has expired.

**Comment by alechenninger** [comment]
+1, sounds good, PR inc...
