### ISSUE TITLE
Update artifact versions to use semantic versioning

### ISSUE THREAD

**Issue by derek63** [esbtools/esb-message-admin#8]
0.0.3-SNAPSHOT for instance (see http://semver.org for more info).  Let's resolve https://github.com/esbtools/esb-message-admin/issues/7 first before making this update

**Comment by vritant** [comment]
fixed in PR #9

**Comment by derek63** [comment]
Not all of the module artifact versions were updated to follow this standard, and they all seem to have different versions.  Will reset all to 0.0.1-SNAPSHOT.

**Comment by derek63** [comment]
Versions updated now, closing
