### ISSUE TITLE
Add test/example data that can be optionally loaded for developers

### ISSUE THREAD

**Issue by derek63** [esbtools/esb-message-admin#93]

**Comment by alechenninger** [comment]
I think we could also incorporate this to automated end-to-end tests. The only thing really holding that up is test data, otherwise I have some Arquillian + darcy POCs that could work to automate UI scenarios. (Such as the error message [not] clearing on search with no results).

**Comment by alechenninger** [comment]
Beyond this we should consider including a docker image or vagrant box which has wildfly or jbossas ready to go with this example data... add maven goals for build+deploy, and you have a reasonably quick feedback cycle :).

**Comment by derek63** [comment]
@alechenninger I added sample data in https://github.com/esbtools/esb-message-admin/pull/112, and have created another issue to have some kind of containerized EMA instance at https://github.com/esbtools/esb-message-admin/issues/113
